runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: bootstrap

- url: /Content
  static_dir: Content

- url: /management
  script: management.app

- url: /create_stream
  script: create_stream.app

- url: /view_stream.*
  script: view_stream.app


- url: /
  script: login.app

- url: /trending_cron
  script: trending_cron.app

- url: /blobstore.*
  script: blob_store_test.app

- url: /searchstream.*
  script: search_stream.app

- url: /all_stream.*
  script: all_stream.app

#- url: /blobstore/serviece
#  script: blob_store_test.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
